#!/bin/sh

set -e

if [ ! -e target/.done ]; then
    mkdir -p target
    curl -sL -o target/s6-overlay-amd64-static.tar.gz https://github.com/just-containers/s6-overlay/releases/download/v1.19.1.1/s6-overlay-amd64.tar.gz
    touch target/.done
fi
